// frontend/src/components/CarCard.vue
<template>
  <div class="car-card" @click="handleClick">
    <!-- Image -->
    <div class="card-image">
      <div class="image-placeholder">
        <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M5 10L3 16L5 16L7 10H5Z" fill="currentColor"/>
          <path d="M19 10L21 16H19L17 10H19Z" fill="currentColor"/>
          <path d="M7 10H17L16 7C15.5 6 14.5 5 12 5C9.5 5 8.5 6 8 7L7 10Z" fill="currentColor"/>
          <path d="M6 12H18L17 18C16.5 19 15.5 20 12 20C8.5 20 7.5 19 7 18L6 12Z" fill="currentColor"/>
        </svg>
      </div>
      <!-- Discount Badge -->
      <div v-if="car.direct_discount > 0" class="discount-badge">
        省 ¥{{ formatPrice(car.direct_discount) }}万
      </div>
    </div>

    <!-- Content -->
    <div class="card-content">
      <!-- Header -->
      <div class="card-header">
        <div class="car-title">
          <span class="brand">{{ car.brand }}</span>
          <span class="model">{{ car.model_name }}</span>
        </div>
        <div class="car-meta">
          <span class="year">{{ car.year }}款</span>
          <span class="divider">·</span>
          <span class="seats">{{ car.seat_count }}座</span>
        </div>
      </div>

      <!-- Tags -->
      <div class="tag-list">
        <span class="tag" :class="`tag-${energyTag.type}`">
          {{ energyTag.text }}
        </span>
        <span class="tag tag-gray">
          {{ bodyTag.text }}
        </span>
      </div>

      <!-- Price -->
      <div class="price-section">
        <div class="price-main">
          <span class="price-currency">¥</span>
          <span class="price-value">{{ formatPrice(car.price_discount) }}</span>
          <span class="price-unit">万</span>
        </div>
        <div class="price-sub">
          <span class="price-original">官方价 ¥{{ formatPrice(car.price_official) }}万</span>
        </div>
      </div>

      <!-- Subsidies -->
      <div v-if="hasSubsidies" class="subsidy-list">
        <div v-if="car.loan_subsidy_amount > 0" class="subsidy-item">
          <span class="subsidy-dot"></span>
          <span>贴息 ¥{{ formatPrice(car.loan_subsidy_amount) }}万</span>
        </div>
        <div v-if="car.replacement_subsidy > 0" class="subsidy-item">
          <span class="subsidy-dot green"></span>
          <span>置换 ¥{{ formatPrice(car.replacement_subsidy) }}万</span>
        </div>
      </div>

      <!-- Footer -->
      <div class="card-footer">
        <span class="region">{{ car.region }}</span>
        <span class="action">
          查看
          <el-icon><ArrowRight /></el-icon>
        </span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useRouter } from 'vue-router';
import { ArrowRight } from '@element-plus/icons-vue';
import type { Car } from '@/types';

interface Props {
  car: Car;
}

const props = defineProps<Props>();
const router = useRouter();

const energyTag = computed(() => {
  const map: Record<string, { type: string; text: string }> = {
    petrol: { type: 'gray', text: '燃油' },
    diesel: { type: 'gray', text: '柴油' },
    hybrid: { type: 'green', text: '混动' },
    phev: { type: 'blue', text: '插混' },
    bev: { type: 'green', text: '纯电' },
    hydrogen: { type: 'orange', text: '氢能' },
  };
  return map[props.car.energy_type] || { type: 'gray', text: props.car.energy_type };
});

const bodyTag = computed(() => {
  const map: Record<string, string> = {
    sedan: '轿车',
    suv: 'SUV',
    mpv: 'MPV',
    hatchback: '两厢',
    coupe: '跑车',
    pickup: '皮卡',
    wagon: '旅行',
  };
  return map[props.car.body_type] || props.car.body_type;
});

const hasSubsidies = computed(() => {
  return (props.car.loan_subsidy_amount && props.car.loan_subsidy_amount > 0) ||
         (props.car.replacement_subsidy && props.car.replacement_subsidy > 0);
});

const formatPrice = (price: number) => price.toFixed(2);

const handleClick = () => {
  router.push(`/car/${props.car.id}`);
};
</script>

<style scoped>
.car-card {
  background: var(--bg-primary);
  border-radius: var(--radius-xl);
  overflow: hidden;
  box-shadow: var(--shadow-sm);
  border: 1px solid var(--border-light);
  transition: all var(--duration-normal) var(--ease-out);
  cursor: pointer;
  height: 100%;
  display: flex;
  flex-direction: column;
}

.car-card:hover {
  transform: translateY(-4px);
  box-shadow: var(--shadow-lg);
  border-color: var(--primary-200);
}

/* Image */
.card-image {
  position: relative;
  aspect-ratio: 16/10;
  background: linear-gradient(135deg, var(--primary-50) 0%, #e0e7ff 100%);
  overflow: hidden;
}

.image-placeholder {
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  color: var(--primary-300);
}

.image-placeholder svg {
  width: 64px;
  height: 64px;
}

.discount-badge {
  position: absolute;
  top: var(--space-3);
  right: var(--space-3);
  background: linear-gradient(135deg, var(--error-500) 0%, var(--error-600) 100%);
  color: white;
  font-size: var(--text-xs);
  font-weight: var(--font-bold);
  padding: var(--space-1) var(--space-3);
  border-radius: var(--radius-full);
  box-shadow: var(--shadow-md);
}

/* Content */
.card-content {
  padding: var(--space-5);
  flex: 1;
  display: flex;
  flex-direction: column;
}

/* Header */
.card-header {
  margin-bottom: var(--space-3);
}

.car-title {
  display: flex;
  align-items: baseline;
  gap: var(--space-2);
  margin-bottom: var(--space-1);
}

.brand {
  font-size: var(--text-lg);
  font-weight: var(--font-bold);
  color: var(--text-primary);
}

.model {
  font-size: var(--text-base);
  color: var(--text-secondary);
}

.car-meta {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  font-size: var(--text-sm);
  color: var(--text-tertiary);
}

.divider {
  color: var(--border-medium);
}

/* Tags */
.tag-list {
  display: flex;
  gap: var(--space-2);
  margin-bottom: var(--space-4);
}

.tag {
  display: inline-flex;
  align-items: center;
  padding: var(--space-1) var(--space-2);
  font-size: var(--text-xs);
  font-weight: var(--font-semibold);
  border-radius: var(--radius-full);
  text-transform: uppercase;
  letter-spacing: 0.025em;
}

.tag-blue {
  background: var(--primary-100);
  color: var(--primary-700);
}

.tag-green {
  background: var(--success-100);
  color: var(--success-600);
}

.tag-orange {
  background: var(--accent-100);
  color: var(--accent-700);
}

.tag-gray {
  background: var(--gray-100);
  color: var(--gray-600);
}

/* Price */
.price-section {
  margin-top: auto;
  padding: var(--space-4) 0;
  border-top: 1px solid var(--border-light);
  border-bottom: 1px solid var(--border-light);
  margin-bottom: var(--space-3);
}

.price-main {
  display: flex;
  align-items: flex-start;
  gap: var(--space-1);
  margin-bottom: var(--space-1);
}

.price-currency {
  font-size: var(--text-lg);
  font-weight: var(--font-bold);
  color: var(--error-600);
  line-height: 1;
}

.price-value {
  font-size: var(--text-3xl);
  font-weight: var(--font-bold);
  color: var(--error-600);
  line-height: 1;
  letter-spacing: -0.02em;
}

.price-unit {
  font-size: var(--text-base);
  font-weight: var(--font-semibold);
  color: var(--error-600);
  line-height: 1.2;
}

.price-sub {
  font-size: var(--text-sm);
  color: var(--text-tertiary);
}

.price-original {
  text-decoration: line-through;
}

/* Subsidies */
.subsidy-list {
  display: flex;
  flex-direction: column;
  gap: var(--space-2);
  margin-bottom: var(--space-4);
}

.subsidy-item {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  font-size: var(--text-sm);
  color: var(--text-secondary);
}

.subsidy-dot {
  width: 6px;
  height: 6px;
  background: var(--accent-500);
  border-radius: var(--radius-full);
}

.subsidy-dot.green {
  background: var(--success-500);
}

/* Footer */
.card-footer {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-top: auto;
}

.region {
  font-size: var(--text-sm);
  color: var(--text-tertiary);
}

.action {
  display: flex;
  align-items: center;
  gap: var(--space-1);
  font-size: var(--text-sm);
  font-weight: var(--font-semibold);
  color: var(--primary-600);
  transition: color var(--duration-fast);
}

.car-card:hover .action {
  color: var(--primary-700);
}

.action .el-icon {
  transition: transform var(--duration-fast);
}

.car-card:hover .action .el-icon {
  transform: translateX(2px);
}

/* Responsive */
@media (max-width: 768px) {
  .card-content {
    padding: var(--space-4);
  }
  
  .brand {
    font-size: var(--text-base);
  }
  
  .model {
    font-size: var(--text-sm);
  }
  
  .price-value {
    font-size: var(--text-2xl);
  }
}
</style>

// frontend/src/components/CarCard.tsx
// ── Car Card Component ─────────────────────────────────────────
import React from 'react';
import { Card, Tag, Space } from 'antd';
import { useNavigate } from 'react-router-dom';
import { Car } from '../types';

const { Meta } = Card;

interface CarCardProps {
  car: Car;
}

export default function CarCard({ car }: CarCardProps) {
  const navigate = useNavigate();

  const getEnergyTag = (type: string) => {
    const map: Record<string, { color: string; text: string }> = {
      petrol: { color: 'default', text: '燃油' },
      diesel: { color: 'default', text: '柴油' },
      hybrid: { color: 'green', text: '混动' },
      phev: { color: 'cyan', text: '插混' },
      bev: { color: 'blue', text: '纯电' },
      hydrogen: { color: 'purple', text: '氢能' },
    };
    const { color, text } = map[type] || { color: 'default', text: type };
    return <Tag color={color}>{text}</Tag>;
  };

  const getBodyTag = (type: string) => {
    const map: Record<string, { color: string; text: string }> = {
      sedan: { color: 'blue', text: '轿车' },
      suv: { color: 'orange', text: 'SUV' },
      mpv: { color: 'purple', text: 'MPV' },
      hatchback: { color: 'geekblue', text: '两厢' },
      coupe: { color: 'magenta', text: '跑车' },
      pickup: { color: 'volcano', text: '皮卡' },
      wagon: { color: 'gold', text: '旅行车' },
    };
    const { color, text } = map[type] || { color: 'default', text: type };
    return <Tag color={color}>{text}</Tag>;
  };

  return (
    <Card
      className="car-card"
      hoverable
      onClick={() => navigate(`/car/${car.id}`)}
      cover={
        <div
          style={{
            height: 160,
            background: `linear-gradient(135deg, #E3F2FD 0%, #BBDEFB 100%)`,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            fontSize: 48,
            color: '#1565C0',
          }}
        >
          🚗
        </div>
      }
    >
      <Meta
        title={
          <div>
            <span style={{ fontSize: 18 }}>{car.brand}</span>
            <span style={{ marginLeft: 8, fontSize: 16, color: '#666' }}>{car.model_name}</span>
          </div>
        }
        description={
          <div>
            <Space wrap style={{ marginBottom: 12 }}>
              {getEnergyTag(car.energy_type)}
              {getBodyTag(car.body_type)}
              {car.seat_count && <Tag>{car.seat_count}座</Tag>}
            </Space>
            <div style={{ marginBottom: 8 }}>
              <span className="price-official">¥{car.price_official.toFixed(2)}万</span>
            </div>
            <div style={{ fontSize: 24, fontWeight: 600, color: '#2E7D32' }}>
              ¥{car.price_discount.toFixed(2)}万
              <span style={{ fontSize: 14, color: '#E65100', marginLeft: 8 }}>
                省¥{car.direct_discount.toFixed(2)}万
              </span>
            </div>
            {car.loan_subsidy_amount && car.loan_subsidy_amount > 0 && (
              <Tag color="orange" style={{ marginTop: 8 }}>
                贴息¥{car.loan_subsidy_amount.toFixed(2)}万
              </Tag>
            )}
          </div>
        }
      />
    </Card>
  );
}
