// frontend-vue/src/components/RecommendationCard.vue
<template>
  <el-card
    class="recommendation-card"
    shadow="hover"
    @click="handleClick"
  >
    <template #header>
      <div class="card-header">
        <div class="rank-badge-container">
          <el-tag
            :type="getRankType(rank)"
            effect="dark"
            class="rank-badge"
          >
            {{ rank }}
          </el-tag>
        </div>
        <div class="car-info">
          <h3 class="car-title">{{ recommendation.car.brand }} {{ recommendation.car.model_name }}</h3>
          <div class="car-tags">
            <el-tag size="small">{{ recommendation.car.year }}款</el-tag>
            <el-tag type="success" size="small">
              ¥{{ recommendation.car.price_discount.toFixed(2) }}万
            </el-tag>
          </div>
        </div>
      </div>
    </template>

    <!-- 风险提醒 -->
    <el-alert
      v-if="recommendation.risk_warning"
      :title="recommendation.risk_warning.message"
      :type="getAlertType(recommendation.risk_warning.level)"
      :description="recommendation.risk_warning.suggestion"
      show-icon
      :closable="false"
      class="risk-alert"
    />

    <!-- 推荐理由 -->
    <div class="recommendation-reason">
      <p><strong>推荐理由：</strong>{{ recommendation.reason }}</p>
    </div>

    <!-- 综合评分 -->
    <div class="score-section">
      <div class="score-header">
        <span>综合评分：</span>
        <el-tag type="primary" size="large" class="score-tag">
          {{ recommendation.score.toFixed(1) }}分
        </el-tag>
      </div>
      <el-progress
        :percentage="recommendation.score"
        :color="'#409EFF'"
        :stroke-width="16"
        :show-text="false"
        class="score-progress"
      />
    </div>

    <!-- 详细评分 -->
    <div class="detail-scores">
      <div class="score-item">
        <div class="score-label">财务健康度</div>
        <el-progress
          :percentage="recommendation.financial_health"
          :color="'#67c23a'"
          :stroke-width="8"
          :show-text="false"
        />
        <span class="score-value">{{ Math.round(recommendation.financial_health) }}</span>
      </div>
      <div class="score-item">
        <div class="score-label">家庭适配度</div>
        <el-progress
          :percentage="recommendation.family_fit"
          :color="'#409eff'"
          :stroke-width="8"
          :show-text="false"
        />
        <span class="score-value">{{ Math.round(recommendation.family_fit) }}</span>
      </div>
      <div class="score-item">
        <div class="score-label">场景匹配度</div>
        <el-progress
          :percentage="recommendation.scenario_match"
          :color="'#e6a23c'"
          :stroke-width="8"
          :show-text="false"
        />
        <span class="score-value">{{ Math.round(recommendation.scenario_match) }}</span>
      </div>
    </div>

    <!-- 价格信息 -->
    <el-divider />
    <div class="price-section">
      <el-row justify="space-between" align="middle">
        <el-col>
          <span class="price-original">
            官方价: ¥{{ recommendation.car.price_official.toFixed(2) }}万
          </span>
        </el-col>
        <el-col class="price-main">
          <span class="price-label">优惠价:</span>
          <span class="price-value">
            ¥{{ recommendation.car.price_discount.toFixed(2) }}万
          </span>
        </el-col>
      </el-row>
      <div v-if="recommendation.car.direct_discount > 0" class="price-save">
        直降 ¥{{ recommendation.car.direct_discount.toFixed(2) }}万
      </div>
      <div v-if="recommendation.car.loan_subsidy_amount && recommendation.car.loan_subsidy_amount > 0" class="loan-subsidy">
        <el-tag type="warning" size="small">
          贴息 ¥{{ recommendation.car.loan_subsidy_amount.toFixed(2) }}万
        </el-tag>
      </div>
    </div>
  </el-card>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useRouter } from 'vue-router';
import type { Recommendation } from '@/types';

interface Props {
  recommendation: Recommendation;
  rank: number;
}

const props = defineProps<Props>();
const router = useRouter();

const getRankType = (rank: number): string => {
  if (rank === 1) return 'danger';
  if (rank === 2) return '';
  if (rank === 3) return 'warning';
  return 'info';
};

const getAlertType = (level: string): 'error' | 'warning' | 'info' => {
  if (level === 'critical') return 'error';
  if (level === 'high') return 'warning';
  return 'info';
};

const handleClick = () => {
  router.push(`/car/${props.recommendation.car.id}`);
};
</script>

<style scoped>
.recommendation-card {
  cursor: pointer;
  transition: all 0.3s;
  height: 100%;
  display: flex;
  flex-direction: column;
}

.recommendation-card:hover {
  transform: translateY(-4px);
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.1);
}

.card-header {
  display: flex;
  align-items: center;
  gap: 12px;
}

.rank-badge-container {
  flex-shrink: 0;
}

.rank-badge {
  font-size: 18px;
  font-weight: bold;
  width: 40px;
  height: 40px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 50%;
}

.car-info {
  flex: 1;
}

.car-title {
  margin: 0 0 8px;
  font-size: 18px;
  font-weight: 600;
  color: #303133;
}

.car-tags {
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
}

.risk-alert {
  margin-bottom: 16px;
}

.recommendation-reason {
  margin-bottom: 16px;
  padding: 12px;
  background-color: #f5f7fa;
  border-radius: 4px;
}

.recommendation-reason p {
  margin: 0;
  line-height: 1.6;
}

.score-section {
  margin-bottom: 16px;
}

.score-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 8px;
}

.score-tag {
  font-size: 16px;
  font-weight: bold;
}

.score-progress {
  width: 100%;
}

.detail-scores {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.score-item {
  display: flex;
  align-items: center;
  gap: 12px;
}

.score-label {
  min-width: 80px;
  font-size: 14px;
  color: #606266;
}

.score-value {
  min-width: 30px;
  font-size: 14px;
  font-weight: bold;
  color: #303133;
}

.price-section {
  padding: 16px;
  background-color: #f5f7fa;
  border-radius: 4px;
}

.price-original {
  color: #909399;
  text-decoration: line-through;
}

.price-main {
  text-align: right;
}

.price-label {
  color: #606266;
  margin-right: 8px;
}

.price-value {
  font-size: 24px;
  font-weight: bold;
  color: #67c23a;
}

.price-save {
  margin-top: 8px;
  color: #f56c6c;
  font-size: 14px;
  text-align: center;
}

.loan-subsidy {
  margin-top: 8px;
  text-align: center;
}
</style>

// frontend/src/components/RecommendationCard.tsx
// ── Recommendation Card Component ───────────────────────────────
import React from 'react';
import { Card, Tag, Progress, Alert, Space } from 'antd';
import { TrophyOutlined, WarningOutlined } from '@ant-design/icons';
import { useNavigate } from 'react-router-dom';
import { Recommendation } from '../types';

interface Props {
  recommendation: Recommendation;
  rank: number;
}

export default function RecommendationCard({ recommendation, rank }: Props) {
  const navigate = useNavigate();
  const { car, score, reason, risk_warning, financial_health, family_fit, scenario_match } = recommendation;

  const getRankColor = (rank: number) => {
    if (rank === 1) return '#FFD700';
    if (rank === 2) return '#C0C0C0';
    if (rank === 3) return '#CD7F32';
    return '#1565C0';
  };

  return (
    <Card
      className="car-card"
      hoverable
      onClick={() => navigate(`/car/${car.id}`)}
      title={
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <div
            style={{
              width: 40,
              height: 40,
              borderRadius: '50%',
              background: getRankColor(rank),
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: '#fff',
              fontWeight: 'bold',
              fontSize: 20,
            }}
          >
            {rank}
          </div>
          <div>
            <div style={{ fontSize: 18 }}>{car.brand} {car.model_name}</div>
            <Space>
              <Tag>{car.year}款</Tag>
              <Tag color="green">¥{car.price_discount.toFixed(2)}万</Tag>
            </Space>
          </div>
        </div>
      }
    >
      {risk_warning && (
        <Alert
          message={risk_warning.message}
          description={risk_warning.suggestion}
          type={risk_warning.level === 'critical' ? 'error' : risk_warning.level === 'high' ? 'warning' : 'info'}
          showIcon
          icon={<WarningOutlined />}
          style={{ marginBottom: 16 }}
        />
      )}

      <div style={{ marginBottom: 16 }}>
        <strong>推荐理由：</strong>
        <span style={{ color: '#666', marginLeft: 8 }}>{reason}</span>
      </div>

      <div style={{ marginBottom: 8 }}>
        <span>综合评分：</span>
        <Progress
          percent={score}
          strokeColor="#1565C0"
          format={(percent) => `${percent?.toFixed(1)}分`}
        />
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 12 }}>
        <div>
          <div style={{ fontSize: 12, color: '#999' }}>财务健康度</div>
          <Progress
            percent={financial_health}
            size="small"
            strokeColor="#2E7D32"
            format={(p) => `${p?.toFixed(0)}`}
          />
        </div>
        <div>
          <div style={{ fontSize: 12, color: '#999' }}>家庭适配度</div>
          <Progress
            percent={family_fit}
            size="small"
            strokeColor="#1565C0"
            format={(p) => `${p?.toFixed(0)}`}
          />
        </div>
        <div>
          <div style={{ fontSize: 12, color: '#999' }}>场景匹配度</div>
          <Progress
            percent={scenario_match}
            size="small"
            strokeColor="#E65100"
            format={(p) => `${p?.toFixed(0)}`}
          />
        </div>
      </div>

      <div style={{ marginTop: 16, padding: 12, background: '#F5F5F5', borderRadius: 8 }}>
        <Row justify="space-between">
          <Col>
            <span style={{ textDecoration: 'line-through', color: '#999' }}>¥{car.price_official.toFixed(2)}万</span>
          </Col>
          <Col>
            <span style={{ color: '#E65100', fontWeight: 600, fontSize: 20 }}>
              ¥{car.price_discount.toFixed(2)}万
            </span>
          </Col>
        </Row>
        {car.direct_discount > 0 && (
          <div style={{ marginTop: 8, color: '#2E7D32', fontSize: 14 }}>
            直降 ¥{car.direct_discount.toFixed(2)}万
          </div>
        )}
        {car.loan_subsidy_amount && car.loan_subsidy_amount > 0 && (
          <Tag color="orange" style={{ marginTop: 8 }}>
            贴息 ¥{car.loan_subsidy_amount.toFixed(2)}万
          </Tag>
        )}
      </div>
    </Card>
  );
}

import { Row, Col } from 'antd';
