// frontend/src/components/Layout/Header.vue
<template>
  <el-header class="app-header">
    <div class="header-container">
      <!-- Logo -->
      <router-link to="/" class="logo-link">
        <el-icon :size="32" color="#409EFF"><Van /></el-icon>
        <span class="logo-text">车价通</span>
      </router-link>

      <!-- Desktop Menu -->
      <el-menu
        v-if="!isMobile"
        mode="horizontal"
        :default-active="currentRoute"
        class="header-menu"
        background-color="#545c64"
        text-color="#fff"
        active-text-color="#ffd04b"
        router
      >
        <el-menu-item index="/">
          <el-icon><HomeFilled /></el-icon>
          <span>首页</span>
        </el-menu-item>
        <el-menu-item index="/search">
          <el-icon><Search /></el-icon>
          <span>搜索</span>
        </el-menu-item>
        <el-menu-item index="/recommend">
          <el-icon><Opportunity /></el-icon>
          <span>推荐</span>
        </el-menu-item>
        <el-menu-item index="/compare">
          <el-icon><Document /></el-icon>
          <span>对比</span>
        </el-menu-item>
        <el-menu-item index="/profile">
          <el-icon><UserFilled /></el-icon>
          <span>我的</span>
        </el-menu-item>
      </el-menu>

      <!-- Search Bar (Desktop) -->
      <el-input
        v-if="!isMobile"
        v-model="searchKeyword"
        placeholder="搜索车型、品牌..."
        class="search-input"
        @keyup.enter="handleSearch"
      >
        <template #prefix>
          <el-icon><Search /></el-icon>
        </template>
        <template #append>
          <el-button @click="handleSearch">搜索</el-button>
        </template>
      </el-input>

      <!-- Mobile Menu Button -->
      <el-button
        v-if="isMobile"
        text
        @click="showMobileMenu = true"
        class="mobile-menu-btn"
      >
        <el-icon :size="24"><Menu /></el-icon>
      </el-button>
    </div>

    <!-- Mobile Menu Drawer -->
    <el-drawer
      v-model="showMobileMenu"
      direction="rtl"
      size="70%"
      :show-close="false"
    >
      <el-menu
        :default-active="currentRoute"
        router
        @select="showMobileMenu = false"
      >
        <el-menu-item index="/">
          <el-icon><HomeFilled /></el-icon>
          <span>首页</span>
        </el-menu-item>
        <el-menu-item index="/search">
          <el-icon><Search /></el-icon>
          <span>搜索</span>
        </el-menu-item>
        <el-menu-item index="/recommend">
          <el-icon><Opportunity /></el-icon>
          <span>推荐</span>
        </el-menu-item>
        <el-menu-item index="/compare">
          <el-icon><Document /></el-icon>
          <span>对比</span>
        </el-menu-item>
        <el-menu-item index="/profile">
          <el-icon><UserFilled /></el-icon>
          <span>我的</span>
        </el-menu-item>
      </el-menu>
      <el-input
        v-model="searchKeyword"
        placeholder="搜索车型、品牌..."
        class="mobile-search"
        @keyup.enter="handleMobileSearch"
      >
        <template #prefix>
          <el-icon><Search /></el-icon>
        </template>
        <template #append>
          <el-button @click="handleMobileSearch">搜索</el-button>
        </template>
      </el-input>
    </el-drawer>
  </el-header>
</template>

<script setup lang="ts">
import { ref, computed, onUnmounted } from 'vue';
import { useRouter, useRoute } from 'vue-router';
import {
  HomeFilled,
  Search,
  Opportunity,
  Document,
  UserFilled,
  Menu,
  Van,
} from '@element-plus/icons-vue';

const router = useRouter();
const route = useRoute();

const searchKeyword = ref('');
const showMobileMenu = ref(false);
const isMobile = ref(window.innerWidth < 768);

const currentRoute = computed(() => route.path);

const handleSearch = () => {
  if (searchKeyword.value.trim()) {
    router.push(`/search?keyword=${encodeURIComponent(searchKeyword.value.trim())}`);
  }
};

const handleMobileSearch = () => {
  handleSearch();
  showMobileMenu.value = false;
};

// 监听窗口大小变化
const handleResize = () => {
  isMobile.value = window.innerWidth < 768;
};

window.addEventListener('resize', handleResize);

// 组件卸载时清理事件监听器
onUnmounted(() => {
  window.removeEventListener('resize', handleResize);
});
</script>

<style scoped>
.app-header {
  background-color: #545c64;
  padding: 0 24px;
  height: 60px;
}

.header-container {
  display: flex;
  align-items: center;
  justify-content: space-between;
  max-width: 1200px;
  margin: 0 auto;
  height: 100%;
}

.logo-link {
  display: flex;
  align-items: center;
  text-decoration: none;
  color: #fff;
}

.logo-text {
  font-size: 20px;
  font-weight: 600;
  margin-left: 8px;
}

.header-menu {
  flex: 1;
  margin-left: 40px;
  border-bottom: none;
}

.search-input {
  width: 300px;
}

.mobile-menu-btn {
  color: #fff;
}

.mobile-search {
  margin-top: 16px;
}

@media (max-width: 768px) {
  .app-header {
    padding: 0 16px;
  }
}
</style>

// frontend/src/components/Layout/Header.tsx
// ── Header Component ────────────────────────────────────────────
import React from 'react';
import { Layout, Menu, Input, Button, Dropdown } from 'antd';
import { Link, useNavigate } from 'react-router-dom';
import {
  HomeOutlined,
  SearchOutlined,
  BulbOutlined,
  DiffOutlined,
  UserOutlined,
  MenuOutlined,
} from '@ant-design/icons';
import { useMediaQuery } from 'react-responsive';
import logo from '/logo.svg';

const { Header: AntHeader } = Layout;
const { Search } = Input;

export default function Header() {
  const navigate = useNavigate();
  const isMobile = useMediaQuery({ maxWidth: 768 });

  const menuItems = [
    { key: 'home', icon: <HomeOutlined />, label: <Link to="/">首页</Link> },
    { key: 'search', icon: <SearchOutlined />, label: <Link to="/search">搜索</Link> },
    { key: 'recommend', icon: <BulbOutlined />, label: <Link to="/recommend">推荐</Link> },
    { key: 'compare', icon: <DiffOutlined />, label: <Link to="/compare">对比</Link> },
    { key: 'profile', icon: <UserOutlined />, label: <Link to="/profile">我的</Link> },
  ];

  const onSearch = (value: string) => {
    if (value.trim()) {
      navigate(`/search?keyword=${encodeURIComponent(value.trim())}`);
    }
  };

  const desktopHeader = (
    <AntHeader>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', maxWidth: 1200, margin: '0 auto' }}>
        <Link to="/" style={{ display: 'flex', alignItems: 'center', textDecoration: 'none' }}>
          <img src={logo} alt="车价通" style={{ height: 40, marginRight: 12 }} />
          <span style={{ color: '#fff', fontSize: 20, fontWeight: 600 }}>车价通</span>
        </Link>
        <Menu
          theme="dark"
          mode="horizontal"
          selectedKeys={[]}
          items={menuItems}
          style={{ flex: 1, marginLeft: 40, minWidth: 0, border: 'none' }}
        />
        <div style={{ marginLeft: 40, minWidth: 300 }}>
          <Search
            placeholder="搜索车型、品牌..."
            allowClear
            enterButton
            onSearch={onSearch}
            style={{ width: '100%' }}
          />
        </div>
      </div>
    </AntHeader>
  );

  const mobileHeader = (
    <AntHeader>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <Link to="/" style={{ display: 'flex', alignItems: 'center', textDecoration: 'none' }}>
          <img src={logo} alt="车价通" style={{ height: 36 }} />
          <span style={{ color: '#fff', fontSize: 18, fontWeight: 600, marginLeft: 8 }}>车价通</span>
        </Link>
        <Dropdown menu={{ items: menuItems }} trigger={['click']}>
          <Button type="text" icon={<MenuOutlined />} style={{ color: '#fff', fontSize: 20 }} />
        </Dropdown>
      </div>
    </AntHeader>
  );

  return isMobile ? mobileHeader : desktopHeader;
}
